[package]
name = "BTF"
version = "0.1.0"
edition = "2021"
authors = ["Rev1le rev1le@vivaldi.net"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.3.0", features= ["v4"] }
md5 = { version = "0.7.0" }